apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "video-service.fullname" . }}
  labels:
    {{- include "video-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "video-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "video-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwtSecret.name }}
                  key: {{ .Values.jwtSecret.key }}
            - name: REDIS_HOST
              value: {{ .Values.env.REDIS_HOST }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
